name: sd2022_s1_env
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - comm=0.1.4
  - debugpy=1.8.0
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.0.0
  - importlib_metadata=7.0.0
  - ipykernel=6.26.0
  - ipython=8.18.1
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - libffi=3.4.2
  - libsodium=1.0.18
  - libsqlite=3.44.2
  - libzlib=1.2.13
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - openssl=3.2.0
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.1.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.9.18
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.3.3
  - traitlets=5.14.0
  - typing_extensions=4.9.0
  - tzdata=2023c
  - wcwidth=0.2.12
  - wheel=0.42.0
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - pip:
      - contourpy==1.2.0
      - cycler==0.12.1
      - fonttools==4.46.0
      - iminuit==2.24.0
      - importlib-resources==6.1.1
      - iniconfig==2.0.0
      - kiwisolver==1.4.5
      - llvmlite==0.41.1
      - matplotlib==3.8.2
      - numba==0.58.1
      - numba-stats==1.4.1
      - numpy==1.26.2
      - pillow==10.1.0
      - pluggy==1.3.0
      - pyparsing==3.1.1
      - pytest==7.4.3
      - resample==1.6.0
      - scipy==1.11.4
      - tabulate==0.9.0
      - tomli==2.0.1
      
